"""llm_pricing_table

Revision ID: 04ce69254bbb
Revises: 4492a2c7b66b
Create Date: 2024-08-28 10:57:10.893998+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04ce69254bbb"
down_revision: Union[str, None] = "4492a2c7b66b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_pricing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.Column("input_price_per_million_tokens", sa.Float(), nullable=False),
        sa.Column("output_price_per_million_tokens", sa.Float(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_llmpricing_model", "llm_pricing", ["model"])
    op.create_index("idx_llmpricing_version", "llm_pricing", ["version"])
    op.create_index("idx_llmpricing_provider", "llm_pricing", ["provider"])
    op.create_index("idx_llmpricing_effective_from", "llm_pricing", ["effective_from"])
    op.create_index("idx_llmpricing_effective_to", "llm_pricing", ["effective_to"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_pricing")
    op.drop_index("idx_llmpricing_model", table_name="llm_pricing")
    op.drop_index("idx_llmpricing_version", table_name="llm_pricing")
    op.drop_index("idx_llmpricing_provider", table_name="llm_pricing")
    op.drop_index("idx_llmpricing_effective_from", table_name="llm_pricing")
    op.drop_index("idx_llmpricing_effective_to", table_name="llm_pricing")
    # ### end Alembic commands ###
