"""Add indexes to fields

Revision ID: 1040ea80bdbd
Revises: a0e45320dd71
Create Date: 2024-05-24 09:17:14.826706+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1040ea80bdbd"
down_revision: Union[str, None] = "a0e45320dd71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_engagement_name", "engagement", ["name"])
    op.create_index("idx_role_name", "roles", ["name"])
    op.create_index("idx_user_email", "users", ["email"])
    op.create_index("idx_project_engagement_id", "project", ["engagement_id"])
    op.create_index("idx_project_name", "project", ["name"])
    op.create_index("idx_user_project_role_user_id", "user_project_roles", ["user_id"])
    op.create_index(
        "idx_user_project_role_project_id", "user_project_roles", ["project_id"]
    )
    op.create_index("idx_user_project_role_role_id", "user_project_roles", ["role_id"])
    op.create_index(
        "idx_batch_run_user_project_role_id", "batch_run", ["user_project_role_id"]
    )
    op.create_index("idx_run_batch_run_id", "run", ["batch_run_id"])
    op.create_index("idx_run_user_project_role_id", "run", ["user_project_role_id"])
    op.create_index("idx_evaluation_run_id", "evaluation", ["run_id"])
    op.create_index("idx_evaluation_batch_run_id", "evaluation", ["batch_run_id"])
    op.create_index("idx_evaluation_evaluator_id", "evaluation", ["evaluator_id"])
    op.create_index("idx_evaluator_type_name", "evaluator_type", ["name"])
    op.create_index(
        "idx_evaluation_config_evaluator_id", "evaluation_configs", ["evaluator_id"]
    )
    op.create_index(
        "idx_evaluator_config_evaluator_id", "evaluator_configs", ["evaluator_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_engagement_name", table_name="engagement")
    op.drop_index("idx_role_name", table_name="roles")
    op.drop_index("idx_user_email", table_name="users")
    op.drop_index("idx_project_engagement_id", table_name="project")
    op.drop_index("idx_project_name", table_name="project")
    op.drop_index("idx_user_project_role_user_id", table_name="user_project_roles")
    op.drop_index("idx_user_project_role_project_id", table_name="user_project_roles")
    op.drop_index("idx_user_project_role_role_id", table_name="user_project_roles")
    op.drop_index("idx_batch_run_user_project_role_id", table_name="batch_run")
    op.drop_index("idx_run_batch_run_id", table_name="run")
    op.drop_index("idx_run_user_project_role_id", table_name="run")
    op.drop_index("idx_evaluation_run_id", table_name="evaluation")
    op.drop_index("idx_evaluation_batch_run_id", table_name="evaluation")
    op.drop_index("idx_evaluation_evaluator_id", table_name="evaluation")
    op.drop_index("idx_evaluator_type_name", table_name="evaluator_type")
    op.drop_index("idx_evaluation_config_evaluator_id", table_name="evaluation_configs")
    op.drop_index("idx_evaluator_config_evaluator_id", table_name="evaluator_configs")
    # ### end Alembic commands ###
