"""message field

Revision ID: 139e92e9c3b4
Revises: 5fce8c12b194
Create Date: 2024-05-20 09:21:43.848244+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139e92e9c3b4'
down_revision: Union[str, None] = '5fce8c12b194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('message', sa.JSON(), nullable=True))
    op.create_index('idx_evaluator_name', 'evaluator', ['name'])
    op.create_index('idx_evaluator_type_id', 'evaluator', ['evaluator_type_id'])
    op.create_index('idx_creator_id', 'evaluator', ['creator_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'message')
    op.drop_index('idx_evaluator_name', 'evaluator')
    op.drop_index('idx_evaluator_type_id', 'evaluator')
    op.drop_index('idx_creator_id', 'evaluator')
    # ### end Alembic commands ###
