"""usermodel changes added service acc details

Revision ID: 20489b342b8a
Revises: b827a9a2d898
Create Date: 2024-05-09 12:28:44.772953+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20489b342b8a'
down_revision: Union[str, None] = 'b827a9a2d898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_id', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('client_secret', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('is_service_account', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'client_id')
    op.drop_column('users', 'client_secret')
    op.drop_column('users', 'is_service_account')
    # ### end Alembic commands ###
