"""add updated_at index for all

Revision ID: 4492a2c7b66b
Revises: 1040ea80bdbd
Create Date: 2024-05-24 14:55:48.462021+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4492a2c7b66b"
down_revision: Union[str, None] = "1040ea80bdbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_engagement_updated_at", "engagement", ["updated_at"])
    op.create_index("idx_role_updated_at", "roles", ["updated_at"])
    op.create_index("idx_user_updated_at", "users", ["updated_at"])
    op.create_index("idx_project_updated_at", "project", ["updated_at"])
    op.create_index(
        "idx_user_project_roles_updated_at", "user_project_roles", ["updated_at"]
    )
    op.create_index("idx_batch_run_updated_at", "batch_run", ["updated_at"])
    op.create_index("idx_run_updated_at", "run", ["updated_at"])
    op.create_index("idx_evaluation_updated_at", "evaluation", ["updated_at"])
    op.create_index("idx_evaluator_type_updated_at", "evaluator_type", ["updated_at"])
    op.create_index("idx_evaluator_updated_at", "evaluator", ["updated_at"])
    op.create_index(
        "idx_evaluation_configs_updated_at", "evaluation_configs", ["updated_at"]
    )
    op.create_index(
        "idx_evaluator_configs_updated_at", "evaluator_configs", ["updated_at"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_engagement_updated_at", table_name="engagement")
    op.drop_index("idx_role_updated_at", table_name="roles")
    op.drop_index("idx_user_updated_at", table_name="users")
    op.drop_index("idx_project_updated_at", table_name="project")
    op.drop_index("idx_user_project_roles_updated_at", table_name="user_project_roles")
    op.drop_index("idx_batch_run_updated_at", table_name="batch_run")
    op.drop_index("idx_run_updated_at", table_name="run")
    op.drop_index("idx_evaluation_updated_at", table_name="evaluation")
    op.drop_index("idx_evaluator_type_updated_at", table_name="evaluator_type")
    op.drop_index("idx_evaluator_updated_at", table_name="evaluator")
    op.drop_index("idx_evaluation_configs_updated_at", table_name="evaluation_configs")
    op.drop_index("idx_evaluator_configs_updated_at", table_name="evaluator_configs")
    # ### end Alembic commands ###
