"""Add uuid token and indexes to evaluations

Revision ID: 5fce8c12b194
Revises: 20489b342b8a
Create Date: 2024-05-15 10:27:28.443887+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fce8c12b194"
down_revision: Union[str, None] = "20489b342b8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evaluation",
        sa.Column(
            "uuid_token",
            sa.String(length=36),
            nullable=False,
        ),
    )
    op.create_index("idx_run_id", "evaluation", ["run_id"])
    op.create_index("idx_batch_run_id", "evaluation", ["batch_run_id"])
    op.create_index("idx_user_project_role_id", "evaluation", ["user_project_role_id"])
    op.create_index("idx_uuid_token", "evaluation", ["uuid_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_uuid_token", table_name="evaluation")
    op.drop_index("idx_user_project_role_id", table_name="evaluation")
    op.drop_index("idx_batch_run_id", table_name="evaluation")
    op.drop_index("idx_run_id", table_name="evaluation")
    op.drop_column("evaluation", "uuid_token")
    # ### end Alembic commands ###
