"""Increase name and email length to 150 and 200

Revision ID: a0e45320dd71
Revises: 139e92e9c3b4
Create Date: 2024-05-22 17:32:11.916387+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0e45320dd71"
down_revision: Union[str, None] = "139e92e9c3b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "engagement",
        "name",
        existing_type=sa.String(length=80),
        type_=sa.String(length=150),
    )
    op.alter_column(
        "roles", "name", existing_type=sa.String(length=50), type_=sa.String(length=150)
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=120),
        type_=sa.String(length=200),
    )
    op.alter_column(
        "users", "name", existing_type=sa.String(length=80), type_=sa.String(length=150)
    )
    op.alter_column(
        "project",
        "name",
        existing_type=sa.String(length=80),
        type_=sa.String(length=150),
    )
    op.alter_column(
        "batch_run",
        "name",
        existing_type=sa.String(length=20),
        type_=sa.String(length=150),
    )
    op.alter_column(
        "evaluation",
        "name",
        existing_type=sa.String(length=80),
        type_=sa.String(length=150),
    )
    op.alter_column(
        "evaluator_type",
        "name",
        existing_type=sa.String(length=80),
        type_=sa.String(length=150),
    )
    op.alter_column(
        "evaluator",
        "name",
        existing_type=sa.String(length=80),
        type_=sa.String(length=150),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "engagement",
        "name",
        existing_type=sa.String(length=150),
        type_=sa.String(length=80),
    )
    op.alter_column(
        "roles", "name", existing_type=sa.String(length=150), type_=sa.String(length=50)
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=200),
        type_=sa.String(length=120),
    )
    op.alter_column(
        "users", "name", existing_type=sa.String(length=150), type_=sa.String(length=80)
    )
    op.alter_column(
        "project",
        "name",
        existing_type=sa.String(length=150),
        type_=sa.String(length=80),
    )
    op.alter_column(
        "batch_run",
        "name",
        existing_type=sa.String(length=150),
        type_=sa.String(length=20),
    )
    op.alter_column(
        "evaluation",
        "name",
        existing_type=sa.String(length=150),
        type_=sa.String(length=80),
    )
    op.alter_column(
        "evaluator_type",
        "name",
        existing_type=sa.String(length=150),
        type_=sa.String(length=80),
    )
    op.alter_column(
        "evaluator",
        "name",
        existing_type=sa.String(length=150),
        type_=sa.String(length=80),
    )
    # ### end Alembic commands ###
